spring:
  data.mongodb.uri: mongodb://flight-api:flight-api-pass@localhost:27017/flight_db
  cloud.stream:
    function.definition: planeArrivedProcessor;flightArrivedConsumer
    kafka:
      bindings:
        planeArrivedProcessor-in-0:
          consumer:
            enableDlq: true
            dlqName: plane-arrived-dlq-v1
        flightArrivedConsumer-in-0:
          consumer:
            enableDlq: true
            dlqName: flight-arrived-dlq-v1
        planeArrivedProcessor-out-0:
          producer.configuration:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
    bindings:
      planeArrivedProcessor-in-0:
        destination: plane-arrived-v1
        group: flight-api
        consumer:
          retryable-exceptions:
            com.henriquels25.flightapi.plane.infra.stream.NoFlightFoundException: false
      planeArrivedProcessor-out-0:
        destination: flight-arrived-v1
      flightArrivedConsumer-in-0:
        destination: flight-arrived-v1
        group: flight-api
      flightFinished-out-0:
        destination: flight-finished-v1

server.port: 8091
